---
- name: Install Nginx package
  apt: pkg=nginx state=present

- name: Copy nginx config
  template: |
    src=albumy_nginx.conf dest=/etc/nginx/sites-enabled/albumy_nginx.conf
    owner=root group=root

- name: Reload nginx
  service: name=nginx state=restarted

